### ISSUE TITLE
SQLiteSpy - про то, где взять.

### ISSUE THREAD

**Issue by Domerk** [db2017ss/syllabus#2]
Вот это место из учебного пособия:
"Графический интерфейс пользователя для доступа к базам данных SQLite для операционной системы Windows предоставляет утилита SQLiteSpy, скачать которую можно здесь:
http://www.yunqa.de/delphi/doku.php/products/sqlitespy/index
Программа не требует инсталляции..."
Хорошо было бы включить в описание 3й лабы. В Вики статьи про SQLiteSpy нет, метод "ищем в Гугле и качаем с первого же попавшегося сайта" не всегда приводит к желаемым результатам, а то, что ссылка может быть в учебном пособии, не самоочевидно :(

**Comment by aksenoff** [comment]
Спасибо, согласен. Пофиксил.
